figure(2)
subplot (2,2,1)
scatter(abs(data(:,find(strcmp(textdata,'Multi Interaction')))),data(:,find(strcmp(textdata,'FR Visual'))))
title('MI vs. FR Visual')
xlabel('Multisensory Interacation')
ylabel('FR Visual')

subplot (2,2,2)
scatter(abs(data(:,find(strcmp(textdata,'Multi Interaction')))),data(:,find(strcmp(textdata,'FR Auditory'))))
title('MI vs. FR Auditory')
xlabel('Multisensory Interacation')
ylabel('FR Auditory')

subplot (2,2,3)
scatter(abs(data(:,find(strcmp(textdata,'Multi Interaction')))),data(:,find(strcmp(textdata,'FR Both'))))
title('MI vs. FR Both')
xlabel('Multisensory Interacation')
ylabel('FR Both')

subplot (2,2,4)
scatter(abs(data(:,find(strcmp(textdata,'Multi Interaction')))),data(:,find(strcmp(textdata,'FR Blank'))))
title('MI vs. FR Blank')
xlabel('Multisensory Interacation')
ylabel('FR Blank')